name=MCP2515
version=0.2.1
author=LoganCarter08
maintainer=LoganCarter08
sentence=Arduino library for MCP2515 CAN controller.
paragraph=Arduino library for MCP2515 CAN controller.
category=Sensors
url=https://github.com/LoganCarter08/MCP2515
architectures=*
depends=Adafruit BusIO
